# Generated by Django 3.0.7 on 2020-12-02 09:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edutech', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Full_chat',
            new_name='Question_Asked',
        ),
    ]
