# Generated by Django 3.0.7 on 2020-12-02 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edutech', '0002_auto_20201202_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_from',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='edutech.Question_Asked')),
            ],
        ),
    ]
