# Generated by Django 3.0.7 on 2020-12-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edutech', '0003_answer_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='edutech.Question_Asked')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer_from',
        ),
    ]
