# Generated by Django 3.0.7 on 2020-12-03 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edutech', '0005_answer_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_model',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='edutech.Question_Asked'),
        ),
    ]
